#!/usr/bin/with-contenv bash

keyFile=/app/config/certs/cert.key
certFile=/app/config/certs/cert.crt
varsFile=/app/config/certs/openssl-vars

if [[ -f ${keyFile} && -f $certFile ]]
then
    echo "Using certificates found in /app/config/certs/"
else
    echo
    echo "Generating self-signed certificates in /app/config/certs/,"
    echo "you can replace these with your own if required"
    echo

    source ${varsFile}

    openssl req \
        -new \
        -x509 \
        -subj "${OPENSSL_SUBJECT}" \
        -days 3650 \
        -nodes \
        -out ${certFile} \
        -keyout ${keyFile} \
        > /dev/null 2>&1
fi
